site_name: Webtechnologie 2
copyright: HG 2025
site_author: Bart Barnard en Ralf van den Broek
site_description: 'Studiemateriaal voor de module webtechnologie 2 van de Hanzehogeschool Groningen'
site_url: 'https://hanze-hbo-ict.github.io/webtech2/'
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'nl'
  features:
     - content.code.copy
  include_sidebar: false
extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra_javascript:
  - js/imgs.js
  - js/matjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
#  - with-pdf
  - search
  - mknotebooks:
      execute: false